<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Build_startup extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Build_startup_model');
    } 

    /*
     * Listing of build_startup
     */
    function index()
    {
        $data['build_startup'] = $this->Build_startup_model->get_all_build_startup();
        
        $data['_view'] = 'build_startup/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new build_startup
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'status' => $this->input->post('status'),
				'timestamp' => $this->input->post('timestamp'),
				'title' => $this->input->post('title'),
				'idea' => $this->input->post('idea'),
				'image' => $this->input->post('image'),
            );
            
            $build_startup_id = $this->Build_startup_model->add_build_startup($params);
            redirect('build_startup/index');
        }
        else
        {            
            $data['_view'] = 'build_startup/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a build_startup
     */
    function edit($id)
    {   
        // check if the build_startup exists before trying to edit it
        $data['build_startup'] = $this->Build_startup_model->get_build_startup($id);
        
        if(isset($data['build_startup']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'status' => $this->input->post('status'),
					'timestamp' => $this->input->post('timestamp'),
					'title' => $this->input->post('title'),
					'idea' => $this->input->post('idea'),
					'image' => $this->input->post('image'),
                );

                $this->Build_startup_model->update_build_startup($id,$params);            
                redirect('build_startup/index');
            }
            else
            {
                $data['_view'] = 'build_startup/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The build_startup you are trying to edit does not exist.');
    } 

    /*
     * Deleting build_startup
     */
    function remove($id)
    {
        $build_startup = $this->Build_startup_model->get_build_startup($id);

        // check if the build_startup exists before trying to delete it
        if(isset($build_startup['id']))
        {
            $this->Build_startup_model->delete_build_startup($id);
            redirect('build_startup/index');
        }
        else
            show_error('The build_startup you are trying to delete does not exist.');
    }
    
}
