<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 require_once 'Course.php';
class Course_slots_time extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Course_slots_time_model');
    } 

    /*
     * Listing of course_slots_time
     */
    function index()
    {
        $data['course_slots_time'] = $this->Course_slots_time_model->get_all_course_slots_time();
        
        $data['_view'] = 'course_slots_time/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new course_slots_time
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'course_id' => $this->input->post('course_id'),
                'time' => $this->input->post('time'),           
             );
            
            $course_slots_time_id = $this->Course_slots_time_model->add_course_slots_time($params);
            redirect('course_slots_time/index');
        }
        else
        {            
            $courses = Course::sharingCoursesList();
            $data['_view'] = 'course_slots_time/add';
            $data['data'] = $courses;
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a course_slots_time
     */
    function edit($id)
    {   
        // check if the course_slots_time exists before trying to edit it
        $data['course_slots_time'] = $this->Course_slots_time_model->get_course_slots_time($id);
        
        if(isset($data['course_slots_time']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'course_id' => $this->input->post('course_id'),
					'time' => $this->input->post('time'),
                );

                $this->Course_slots_time_model->update_course_slots_time($id,$params);            
                redirect('course_slots_time/index');
            }
            else
            {
                $data['_view'] = 'course_slots_time/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The course_slots_time you are trying to edit does not exist.');
    } 

    /*
     * Deleting course_slots_time
     */
    function remove($id)
    {
        $course_slots_time = $this->Course_slots_time_model->get_course_slots_time($id);

        // check if the course_slots_time exists before trying to delete it
        if(isset($course_slots_time['id']))
        {
            $this->Course_slots_time_model->delete_course_slots_time($id);
            redirect('course_slots_time/index');
        }
        else
            show_error('The course_slots_time you are trying to delete does not exist.');
    }
    
}
