<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Course extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Course_model');

    } 

    /*
     * Listing of courses
     */
    function index()
    {
        $data['courses'] = $this->Course_model->get_all_courses();
        
        $data['_view'] = 'course/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new course
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'points' => $this->input->post('points'),
				'userId' => $this->input->post('userId'),
				'title' => $this->input->post('title'),
				'image' => $this->input->post('image'),
            );
            
            $course_id = $this->Course_model->add_course($params);
            redirect('course/index');
        }
        else
        {            
            $data['_view'] = 'course/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a course
     */
    function edit($id)
    {   
        // check if the course exists before trying to edit it
        $data['course'] = $this->Course_model->get_course($id);
        
        if(isset($data['course']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'points' => $this->input->post('points'),
                    'userId' => $this->input->post('userId'),
                    
					'title' => $this->input->post('title'),
					'image' => $this->input->post('image'),
                );

                $this->Course_model->update_course($id,$params);            
                redirect('course/index');
            }
            else
            {
                $data['_view'] = 'course/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The course you are trying to edit does not exist.');
    } 

    /*
     * Deleting course
     */
    function remove($id)
    {
        $course = $this->Course_model->get_course($id);

        // check if the course exists before trying to delete it
        if(isset($course['id']))
        {
            $this->Course_model->delete_course($id);
            redirect('course/index');
        }
        else
            show_error('The course you are trying to delete does not exist.');
    }

    public static function sharingCoursesList() 
    {
        $ci = &get_instance();
        $ci->load->model('Course_model');
        return $ci->Course_model->get_all_courses();
        
    }
    
}
