<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
require_once 'Course.php';

class Course_slots_date extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Course_slots_date_model');
    } 

    /*
     * Listing of course_slots_dates
     */
    function index()
    {
        $data['course_slots_dates'] = $this->Course_slots_date_model->get_all_course_slots_dates();
        
        $data['_view'] = 'course_slots_date/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new course_slots_date
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'course_id' => $this->input->post('course_id'),
				'date' => $this->input->post('date'),
            );
            
            $course_slots_date_id = $this->Course_slots_date_model->add_course_slots_date($params);
            redirect('course_slots_date/index');
           
        }
        else
        {            
            $courses = Course::sharingCoursesList();
            $data['_view'] = 'course_slots_date/add';
            $data['data'] = $courses;
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a course_slots_date
     */
    function edit($id)
    {   
        // check if the course_slots_date exists before trying to edit it
        $data['course_slots_date'] = $this->Course_slots_date_model->get_course_slots_date($id);
        
        if(isset($data['course_slots_date']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'course_id' => $this->input->post('course_id'),
					'date' => $this->input->post('date'),
                );

                $this->Course_slots_date_model->update_course_slots_date($id,$params);            
                redirect('course_slots_date/index');
            }
            else
            {
                $data['_view'] = 'course_slots_date/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The course_slots_date you are trying to edit does not exist.');
    } 

    /*
     * Deleting course_slots_date
     */
    function remove($id)
    {
        $course_slots_date = $this->Course_slots_date_model->get_course_slots_date($id);

        // check if the course_slots_date exists before trying to delete it
        if(isset($course_slots_date['id']))
        {
            $this->Course_slots_date_model->delete_course_slots_date($id);
            redirect('course_slots_date/index');
        }
        else
            show_error('The course_slots_date you are trying to delete does not exist.');
    }
    
}
