<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Doubt extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Doubt_model');
    } 

    /*
     * Listing of doubts
     */
    function index()
    {
        $data['doubts'] = $this->Doubt_model->get_all_doubts();
        
        $data['_view'] = 'doubt/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new doubt
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'status' => $this->input->post('status'),
				'timestamp' => $this->input->post('timestamp'),
				'title' => $this->input->post('title'),
				'idea' => $this->input->post('idea'),
				'image' => $this->input->post('image'),
            );
            
            $doubt_id = $this->Doubt_model->add_doubt($params);
            redirect('doubt/index');
        }
        else
        {            
            $data['_view'] = 'doubt/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a doubt
     */
    function edit($id)
    {   
        // check if the doubt exists before trying to edit it
        $data['doubt'] = $this->Doubt_model->get_doubt($id);
        
        if(isset($data['doubt']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'status' => $this->input->post('status'),
					'timestamp' => $this->input->post('timestamp'),
					'title' => $this->input->post('title'),
					'idea' => $this->input->post('idea'),
					'image' => $this->input->post('image'),
                );

                $this->Doubt_model->update_doubt($id,$params);            
                redirect('doubt/index');
            }
            else
            {
                $data['_view'] = 'doubt/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The doubt you are trying to edit does not exist.');
    } 

    /*
     * Deleting doubt
     */
    function remove($id)
    {
        $doubt = $this->Doubt_model->get_doubt($id);

        // check if the doubt exists before trying to delete it
        if(isset($doubt['id']))
        {
            $this->Doubt_model->delete_doubt($id);
            redirect('doubt/index');
        }
        else
            show_error('The doubt you are trying to delete does not exist.');
    }
    
}
