<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Workshop extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Workshop_model');
    } 

    /*
     * Listing of workshops
     */
    function index()
    {
        $data['workshops'] = $this->Workshop_model->get_all_workshops();
        
        $data['_view'] = 'workshop/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new workshop
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'user_id' => $this->input->post('user_id'),
				'status' => $this->input->post('status'),
				'title' => $this->input->post('title'),
				'description' => $this->input->post('description'),
				'image' => $this->input->post('image'),
            );
            
            $workshop_id = $this->Workshop_model->add_workshop($params);
            redirect('workshop/index');
        }
        else
        {            
            $data['_view'] = 'workshop/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a workshop
     */
    function edit($id)
    {   
        // check if the workshop exists before trying to edit it
        $data['workshop'] = $this->Workshop_model->get_workshop($id);
        
        if(isset($data['workshop']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'user_id' => $this->input->post('user_id'),
					'status' => $this->input->post('status'),
					'title' => $this->input->post('title'),
					'description' => $this->input->post('description'),
					'image' => $this->input->post('image'),
                );

                $this->Workshop_model->update_workshop($id,$params);            
                redirect('workshop/index');
            }
            else
            {
                $data['_view'] = 'workshop/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The workshop you are trying to edit does not exist.');
    } 

    /*
     * Deleting workshop
     */
    function remove($id)
    {
        $workshop = $this->Workshop_model->get_workshop($id);

        // check if the workshop exists before trying to delete it
        if(isset($workshop['id']))
        {
            $this->Workshop_model->delete_workshop($id);
            redirect('workshop/index');
        }
        else
            show_error('The workshop you are trying to delete does not exist.');
    }
    
}
