<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Build_startup_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get build_startup by id
     */
    function get_build_startup($id)
    {
        return $this->db->get_where('build_startup',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all build_startup
     */
    function get_all_build_startup()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('build_startup')->result_array();
    }
        
    /*
     * function to add new build_startup
     */
    function add_build_startup($params)
    {
        $this->db->insert('build_startup',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update build_startup
     */
    function update_build_startup($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('build_startup',$params);
    }
    
    /*
     * function to delete build_startup
     */
    function delete_build_startup($id)
    {
        return $this->db->delete('build_startup',array('id'=>$id));
    }
}
