<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Course_topic_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get course_topic by id
     */
    function get_course_topic($id)
    {
        return $this->db->get_where('course_topics',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all course_topics
     */
    function get_all_course_topics()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('course_topics')->result_array();
    }
        
    /*
     * function to add new course_topic
     */
    function add_course_topic($params)
    {
        $this->db->insert('course_topics',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update course_topic
     */
    function update_course_topic($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('course_topics',$params);
    }
    
    /*
     * function to delete course_topic
     */
    function delete_course_topic($id)
    {
        return $this->db->delete('course_topics',array('id'=>$id));
    }
}
