<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Course_slots_time_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get course_slots_time by id
     */
    function get_course_slots_time($id)
    {
        return $this->db->get_where('course_slots_time',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all course_slots_time
     */
    function get_all_course_slots_time()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('course_slots_time')->result_array();
    }
        
    /*
     * function to add new course_slots_time
     */
    function add_course_slots_time($params)
    {
        $this->db->insert('course_slots_time',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update course_slots_time
     */
    function update_course_slots_time($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('course_slots_time',$params);
    }
    
    /*
     * function to delete course_slots_time
     */
    function delete_course_slots_time($id)
    {
        return $this->db->delete('course_slots_time',array('id'=>$id));
    }
}
