<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Doubt_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get doubt by id
     */
    function get_doubt($id)
    {
        return $this->db->get_where('doubts',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all doubts
     */
    function get_all_doubts()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('doubts')->result_array();
    }
        
    /*
     * function to add new doubt
     */
    function add_doubt($params)
    {
        $this->db->insert('doubts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update doubt
     */
    function update_doubt($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('doubts',$params);
    }
    
    /*
     * function to delete doubt
     */
    function delete_doubt($id)
    {
        return $this->db->delete('doubts',array('id'=>$id));
    }
}
