<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Internship_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get internship by id
     */
    function get_internship($id)
    {
        return $this->db->get_where('internships',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all internships
     */
    function get_all_internships()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('internships')->result_array();
    }
        
    /*
     * function to add new internship
     */
    function add_internship($params)
    {
        $this->db->insert('internships',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update internship
     */
    function update_internship($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('internships',$params);
    }
    
    /*
     * function to delete internship
     */
    function delete_internship($id)
    {
        return $this->db->delete('internships',array('id'=>$id));
    }
}
