<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Job_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get job by id
     */
    function get_job($id)
    {
        return $this->db->get_where('jobs',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all jobs
     */
    function get_all_jobs()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('jobs')->result_array();
    }
        
    /*
     * function to add new job
     */
    function add_job($params)
    {
        $this->db->insert('jobs',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update job
     */
    function update_job($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('jobs',$params);
    }
    
    /*
     * function to delete job
     */
    function delete_job($id)
    {
        return $this->db->delete('jobs',array('id'=>$id));
    }
}
