<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Transaction_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get transaction by id
     */
    function get_transaction($id)
    {
        return $this->db->get_where('transactions',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all transactions
     */
    function get_all_transactions()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('transactions')->result_array();
    }
        
    /*
     * function to add new transaction
     */
    function add_transaction($params)
    {
        $this->db->insert('transactions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update transaction
     */
    function update_transaction($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('transactions',$params);
    }
    
    /*
     * function to delete transaction
     */
    function delete_transaction($id)
    {
        return $this->db->delete('transactions',array('id'=>$id));
    }
}
