<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Workshop_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get workshop by id
     */
    function get_workshop($id)
    {
        return $this->db->get_where('workshops',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all workshops
     */
    function get_all_workshops()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('workshops')->result_array();
    }
        
    /*
     * function to add new workshop
     */
    function add_workshop($params)
    {
        $this->db->insert('workshops',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update workshop
     */
    function update_workshop($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('workshops',$params);
    }
    
    /*
     * function to delete workshop
     */
    function delete_workshop($id)
    {
        return $this->db->delete('workshops',array('id'=>$id));
    }
}
